### PR TITLE
Add support save result to file

### PR DESCRIPTION
**Pull request by p0we7**

### CODE REVIEW

**Comment by xykt** [comment]
Thank you for your PR. Using -s to save the result to a file is a good idea, but before merging, please make the following changes:
1. Providing a save path parameter is necessary (e.g., -s /Path/to/ResultFile), as writing results in any current directory could clutter the file system.
2. The script should clearly prompt the user and require a yes/no confirmation before making any changes to the disk, ensuring the user (especially those who copy and paste) is informed about writing files (this is one of the principles of this script).
3. The variable $ip_report contains a large number of ANSI escape characters, and outputting it directly as a text file would not be readable, which may confuse users. Please ensure the output file is readable.

**Comment by p0we7** [comment]
@xykt  Thank you for your suggestion, here are a few questions of mine.

Can I reply in Chinese? This time, I'll use two languages.

1. I will submit a new commit.

2. The reason I consider saving the file is that the script can complete the check unattended. Then, should we add a parameter so that the script does not require user confirmation? Or does the script not want to have this unattended mode?

3. From the part of the code I have read so far, I only understand that the final report is obtained through $ip_report. If the report needs to be displayed, `echo filename.txt` is used to display the report. If ANSI characters are removed, does the main code have a function to save the corresponding report?

<details>

<summary>中文</summary>

1. 我将会提交提交新的commit 。
2. 我考虑保存文件的原因是另脚本可以无人值守完成检查，那么还应该增加一个参数以便于脚本无需用户确认。还是说脚本不希望有这种无人值守的时候存在。
3. 在我目前看来我阅读的部分代码来看，只理解到通过 $ip_report 获取到最终报告，如果要展示报告则需要 `echo filename.txt`  来展示报告。如果去掉 ANSI字符的话，主线代码是否有一个函数保存相对应的报告？

</details>

**Comment by xykt** [comment]
感谢反馈。如果是二次开发用于无人值守的检查，其实可以更简单地采用以下方法，而无需改动任何脚本代码：
- 输出文件 `bash <(curl -sL IP.Check.Place) >> /Path/to/Output.ansi`
- 查看格式化结果 `echo "$(cat /Path/to/output.ansi)"`

关于$ip_report，由于您pr中输出是txt文件，我所以自然而然地认为ansi code不应输出为plain text后缀文件，可能是我对您的意图有误解，抱歉。
此外，需要您注意，如果使用本脚本进行无人值守完成检查，必须要提前确认目标系统已安装必要依赖，因为脚本在检测到缺乏依赖的时候，也会弹出yes/no的确认，让用户选择是否安装相应依赖。如果忽视对于依赖的检查，脚本也同样无法自动输出结果。
最后，您希望提交新的commit，那我就先关闭这个了，不过有问题您可以继续在此留言，如有必要也可以reopen，谢谢！

**Comment by p0we7** [comment]
`bash <(curl -sL IP.Check.Place) >> /Path/to/Output.ansi`

如果直接用这个命令输出，我试过它会把整个检测过程都会保存进去，而不是只有结果。

而 yes/no 安装依赖的问题，我现在是再用一个脚本先装依赖再套用本脚本。所以我才考虑是否加一个参数实现无人值守。

我用 txt 的原因是不知道有 `*.ansi `这种文件格式。

**Pull request closed without merging**
